export const ARROW_UP_KEY = 'ArrowUp'
export const ARROW_DOWN_KEY = 'ArrowDown'
export const ARROW_LEFT_KEY = 'ArrowLeft'
export const ARROW_RIGHT_KEY = 'ArrowRight'
export const DELETE_KEY = 'Delete'
export const TAB_KEY = 'Tab'
